[project]
name = "3d-web-viz"
version = "0.1.0"
description = "3D web visualization experiments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygltflib>=1.16.2",
    "usd-core>=24.8",
]
